package org.sagebionetworks.web.server.servlet;

import java.util.List;
import org.json.JSONObject;

/**
 * Translates
 *  - a list of files processed by Vite
 *  - a manifest generated by Vite (production only)
 * into HTML scripts that allow the browser to access the correct assets.
 */
public interface ViteHTMLGenerator {
  String getViteDevelopmentHTML(List<String> filesToImport);

  String getViteProductionHTML(
    List<String> filesToImport,
    JSONObject manifest,
    String assetPath
  );
}
