package org.sagebionetworks.web.server.servlet;

import org.json.JSONObject;

/**
 * Provides the serialized manifest.json object generated by `vite build`
 */
public interface ViteManifestProvider {
  JSONObject getManifest();
}
