package org.sagebionetworks.web.client.widget.entity.controller;

import com.google.gwt.user.client.ui.IsWidget;
import org.sagebionetworks.repo.model.entitybundle.v2.EntityBundle;
import org.sagebionetworks.web.client.place.Synapse.EntityArea;
import org.sagebionetworks.web.client.widget.entity.file.AddToDownloadListV2;
import org.sagebionetworks.web.client.widget.entity.menu.v3.EntityActionMenu;

/**
 * Abstraction for a controller that executes basic entity actions from events generated by a shared
 * action menu.
 *
 * @author jhill
 *
 */
public interface EntityActionController extends IsWidget {
  /**
   * Configure this controller for a given entity
   *
   * @param actionMenu
   * @param entityBundle
   * @param isCurrentVersion
   */
  public void configure(
    EntityActionMenu actionMenu,
    EntityBundle entityBundle,
    boolean isCurrentVersion,
    String wikiPageKey,
    EntityArea currentArea,
    AddToDownloadListV2 addToDownloadListWidget
  );

  /**
   * Delete action selected
   */
  public void onDeleteEntity();

  /**
   * Share dialog selected.
   */
  public void onShare();

  void setIsShowingVersion(boolean isShowingVersion);
}
