package org.sagebionetworks.web.client.widget.entity;


/**
 * The enumeration of possible actions from the Markdown Editor
 * 
 * @author Jay
 *
 */
public enum MarkdownEditorAction {

	EDIT_WIDGET,
	INSERT_ATTACHMENT,
	INSERT_BUTTON_LINK,
	INSERT_ENTITY_LIST,
	INSERT_IMAGE,
	INSERT_JOIN_TEAM,
	INSERT_LINK,
	INSERT_PROV_GRAPH,
	INSERT_QUERY_TABLE,
	INSERT_REFERENCE,
	INSERT_SUBMIT_TO_EVALUATION,
	INSERT_TABLE,
	INSERT_TOC,
	INSERT_USER_TEAM_BADGE,
	INSERT_VIDEO,
	INSERT_YOU_TUBE,
	//alpha
	INSERT_BOOKMARK,
	INSERT_SYNAPSE_TABLE,
	INSERT_EXTERNAL_WEBSITE,
	INSERT_API_SUPERTABLE,
	INSERT_API_SUPERBUTTON,
	INSERT_WIKI_FILES_PREVIEW,
	INSERT_TUTORIAL_WIZARD,
	INSERT_REGISTER_CHALLENGE_TEAM,
	INSERT_CHALLENGE_TEAMS,
	INSERT_CHALLENGE_PARTICIPANTS,
	SET_PROJECT_BACKGROUND,
	BOLD,
	ITALIC,
	STRIKETHROUGH,
	CODE_BLOCK,
	MATH,
	SUBSCRIPT,
	SUPERSCRIPT,
	H1,
	H2,
	H3,
	H4,
	H5,
	H6,
	SAVE,
	PREVIEW,
	CANCEL,
	DELETE
}
