package org.sagebionetworks.web.client.widget.entity;


/**
 * The enumeration of possible actions from the Markdown Editor
 * 
 * @author Jay
 *
 */
public enum MarkdownEditorAction {

	EDIT_WIDGET, INSERT_ATTACHMENT, INSERT_BIODALLIANCE_GENOME_BROWSER, INSERT_CYTOSCAPE_JS, INSERT_BUTTON_LINK, INSERT_ENTITY_LIST, INSERT_IMAGE, INSERT_IMAGE_LINK, INSERT_JOIN_TEAM, INSERT_LINK, INSERT_DETAILS_SUMMARY, INSERT_PROV_GRAPH, INSERT_QUERY_TABLE, INSERT_LEADERBOARD, INSERT_REFERENCE, INSERT_SUBMIT_TO_EVALUATION, INSERT_TABLE, INSERT_TOC, INSERT_USER_LINK, INSERT_USER_TEAM_BADGE, INSERT_VIDEO, INSERT_GRAPH,
	// alpha
	INSERT_SYNAPSE_TABLE, INSERT_EXTERNAL_WEBSITE, INSERT_API_SUPERTABLE, INSERT_WIKI_FILES_PREVIEW, INSERT_TUTORIAL_WIZARD, INSERT_REGISTER_CHALLENGE_TEAM, INSERT_CHALLENGE_TEAMS, INSERT_CHALLENGE_PARTICIPANTS, INSERT_SYNAPSE_FORM, INSERT_PREVIEW, SET_PROJECT_BACKGROUND, MARKDOWN_PREVIEW, INSERT_TEAM_MEMBERS, INSERT_TEAM_MEMBER_COUNT, BOLD, ITALIC, STRIKETHROUGH, CODE_BLOCK, MATH, SUBSCRIPT, SUPERSCRIPT, H1, H2, H3, H4, H5, H6, SAVE, PREVIEW, CANCEL, DELETE
}
