package org.sagebionetworks.web.client;

public enum FeatureFlagKey {
  PROVENANCE_V2_VISUALIZATION("PROVENANCE_V2_VISUALIZATION"),
  GOOGLE_MAP("GOOGLE_MAP"),
  VIEW_ASSOCIATED_PROJECTS("VIEW_ASSOCIATED_PROJECTS"),
  PROVENANCE_DOCKER_IMAGES("PROVENANCE_DOCKER_IMAGES"),
  DESCRIPTION_FIELD("DESCRIPTION_FIELD"),
  ADD_WIKI_WIDGETS("ADD_WIKI_WIDGETS"),
  WIKI_DIFF_TOOL("WIKI_DIFF_TOOL"),
  CUSTOM_STORAGE_LOCATION_SETTINGS("CUSTOM_STORAGE_LOCATION_SETTINGS"),
  CHALLENGE_SUBMISSION_SETTINGS("CHALLENGE_SUBMISSION_SETTINGS"),
  SRC_BASED_AR_MODAL_WIZARD("SRC_BASED_AR_MODAL_WIZARD"),
  HOMEPAGE_V2("HOMEPAGE_V2");

  private final String key;

  FeatureFlagKey(String key) {
    this.key = key;
  }

  public String getKey() {
    return key;
  }
}
