package org.sagebionetworks.web.shared.users;

public enum PermissionLevel {
	CAN_VIEW, CAN_EDIT, CAN_EDIT_DELETE, CAN_ADMINISTER, CAN_SCORE_EVALUATION, CAN_PARTICIPATE_EVALUATION, CAN_ADMINISTER_EVALUATION
}
