package org.sagebionetworks.web.shared.users;

public enum PermissionLevel {
  CAN_VIEW,
  CAN_DOWNLOAD,
  CAN_EDIT,
  CAN_EDIT_DELETE,
  CAN_ADMINISTER,
  CAN_SCORE_EVALUATION,
  CAN_SUBMIT_EVALUATION,
  CAN_ADMINISTER_EVALUATION,
  CAN_MESSAGE_TEAM,
  CAN_ADMINISTER_TEAM,
  CAN_REVIEW_SUBMISSIONS,
}
