(function(k,z){"object"===typeof exports&&"undefined"!==typeof module?module.exports=z():"function"===typeof define&&define.amd?define(z):k.moment=z()})(this,function(){function k(){return Va.apply(null,arguments)}function z(a){return"[object Array]"===Object.prototype.toString.call(a)}function ja(a){return a instanceof Date||"[object Date]"===Object.prototype.toString.call(a)}function Wa(a,b){var c=[],d;for(d=0;d<a.length;++d)c.push(b(a[d],d));return c}function G(a,b){return Object.prototype.hasOwnProperty.call(a,
b)}function ka(a,b){for(var c in b)G(b,c)&&(a[c]=b[c]);G(b,"toString")&&(a.toString=b.toString);G(b,"valueOf")&&(a.valueOf=b.valueOf);return a}function W(a,b,c,d){return Xa(a,b,c,d,!0).utc()}function n(a){null==a._pf&&(a._pf={empty:!1,unusedTokens:[],unusedInput:[],overflow:-2,charsLeftOver:0,nullInput:!1,invalidMonth:null,invalidFormat:!1,userInvalidated:!1,iso:!1});return a._pf}function Ba(a){if(null==a._isValid){var b=n(a);a._isValid=!isNaN(a._d.getTime())&&0>b.overflow&&!b.empty&&!b.invalidMonth&&
!b.invalidWeekday&&!b.nullInput&&!b.invalidFormat&&!b.userInvalidated;a._strict&&(a._isValid=a._isValid&&0===b.charsLeftOver&&0===b.unusedTokens.length&&void 0===b.bigHour)}return a._isValid}function la(a){var b=W(NaN);null!=a?ka(n(b),a):n(b).userInvalidated=!0;return b}function w(a){return void 0===a}function Ca(a,b){var c,d,g;w(b._isAMomentObject)||(a._isAMomentObject=b._isAMomentObject);w(b._i)||(a._i=b._i);w(b._f)||(a._f=b._f);w(b._l)||(a._l=b._l);w(b._strict)||(a._strict=b._strict);w(b._tzm)||
(a._tzm=b._tzm);w(b._isUTC)||(a._isUTC=b._isUTC);w(b._offset)||(a._offset=b._offset);w(b._pf)||(a._pf=n(b));w(b._locale)||(a._locale=b._locale);if(0<Da.length)for(c in Da)d=Da[c],g=b[d],w(g)||(a[d]=g);return a}function ca(a){Ca(this,a);this._d=new Date(null!=a._d?a._d.getTime():NaN);!1===Ea&&(Ea=!0,k.updateOffset(this),Ea=!1)}function L(a){return a instanceof ca||null!=a&&null!=a._isAMomentObject}function x(a){return 0>a?Math.ceil(a):Math.floor(a)}function m(a){a=+a;var b=0;0!==a&&isFinite(a)&&(b=
x(a));return b}function Ya(a,b,c){var d=Math.min(a.length,b.length),g=Math.abs(a.length-b.length),e=0,f;for(f=0;f<d;f++)(c&&a[f]!==b[f]||!c&&m(a[f])!==m(b[f]))&&e++;return e+g}function Za(){}function $a(a){return a?a.toLowerCase().replace("_","-"):a}function ab(a){var b=null;if(!Q[a]&&"undefined"!==typeof module&&module&&module.exports)try{b=ma._abbr,require("./locale/"+a),da(b)}catch(c){}return Q[a]}function da(a,b){var c;a&&(c=w(b)?R(a):bb(a,b))&&(ma=c);return ma._abbr}function bb(a,b){if(null!==
b)return b.abbr=a,Q[a]=Q[a]||new Za,Q[a].set(b),da(a),Q[a];delete Q[a];return null}function R(a){var b;a&&a._locale&&a._locale._abbr&&(a=a._locale._abbr);if(!a)return ma;if(!z(a)){if(b=ab(a))return b;a=[a]}a:{b=0;for(var c,d,g,e;b<a.length;){e=$a(a[b]).split("-");c=e.length;for(d=(d=$a(a[b+1]))?d.split("-"):null;0<c;){if(g=ab(e.slice(0,c).join("-"))){a=g;break a}if(d&&d.length>=c&&Ya(e,d,!0)>=c-1)break;c--}b++}a=null}return a}function v(a,b){var c=a.toLowerCase();ea[c]=ea[c+"s"]=ea[b]=a}function A(a){return"string"===
typeof a?ea[a]||ea[a.toLowerCase()]:void 0}function cb(a){var b={},c,d;for(d in a)G(a,d)&&(c=A(d))&&(b[c]=a[d]);return b}function M(a){return a instanceof Function||"[object Function]"===Object.prototype.toString.call(a)}function X(a,b){return function(c){if(null!=c){if(this.isValid())this._d["set"+(this._isUTC?"UTC":"")+a](c);k.updateOffset(this,b);return this}return na(this,a)}}function na(a,b){return a.isValid()?a._d["get"+(a._isUTC?"UTC":"")+b]():NaN}function db(a,b){var c;if("object"===typeof a)for(c in a)this.set(c,
a[c]);else if(a=A(a),M(this[a]))return this[a](b);return this}function H(a,b,c){var d=""+Math.abs(a);return(0<=a?c?"+":"":"-")+Math.pow(10,Math.max(0,b-d.length)).toString().substr(1)+d}function h(a,b,c,d){var g=d;"string"===typeof d&&(g=function(){return this[d]()});a&&(Y[a]=g);b&&(Y[b[0]]=function(){return H(g.apply(this,arguments),b[1],b[2])});c&&(Y[c]=function(){return this.localeData().ordinal(g.apply(this,arguments),a)})}function Lb(a){return a.match(/\[[\s\S]/)?a.replace(/^\[|\]$/g,""):a.replace(/\\/g,
"")}function Mb(a){var b=a.match(eb),c,d;c=0;for(d=b.length;c<d;c++)b[c]=Y[b[c]]?Y[b[c]]:Lb(b[c]);return function(g){var e="";for(c=0;c<d;c++)e+=b[c]instanceof Function?b[c].call(g,a):b[c];return e}}function Fa(a,b){if(!a.isValid())return a.localeData().invalidDate();b=fb(b,a.localeData());Ga[b]=Ga[b]||Mb(b);return Ga[b](a)}function fb(a,b){function c(a){return b.longDateFormat(a)||a}var d=5;for(oa.lastIndex=0;0<=d&&oa.test(a);)a=a.replace(oa,c),oa.lastIndex=0,--d;return a}function f(a,b,c){Ha[a]=
M(b)?b:function(a,g){return a&&c?c:b}}function Nb(a,b){return G(Ha,a)?Ha[a](b._strict,b._locale):new RegExp(Ob(a))}function Ob(a){return pa(a.replace("\\","").replace(/\\(\[)|\\(\])|\[([^\]\[]*)\]|\\(.)/g,function(a,c,d,g,e){return c||d||g||e}))}function pa(a){return a.replace(/[-\/\\^$*+?.()|[\]{}]/g,"\\$&")}function q(a,b){var c,d=b;"string"===typeof a&&(a=[a]);"number"===typeof b&&(d=function(a,c){c[b]=m(a)});for(c=0;c<a.length;c++)Ia[a[c]]=d}function fa(a,b){q(a,function(a,d,g,e){g._w=g._w||{};
b(a,g._w,g,e)})}function Ja(a,b){return(new Date(Date.UTC(a,b+1,0))).getUTCDate()}function gb(a,b){var c;if(!a.isValid()||"string"===typeof b&&(b=a.localeData().monthsParse(b),"number"!==typeof b))return a;c=Math.min(a.date(),Ja(a.year(),b));a._d["set"+(a._isUTC?"UTC":"")+"Month"](b,c);return a}function hb(a){return null!=a?(gb(this,a),k.updateOffset(this,!0),this):na(this,"Month")}function ib(){function a(a,b){return b.length-a.length}var b=[],c=[],d=[],g,e;for(g=0;12>g;g++)e=W([2E3,g]),b.push(this.monthsShort(e,
"")),c.push(this.months(e,"")),d.push(this.months(e,"")),d.push(this.monthsShort(e,""));b.sort(a);c.sort(a);d.sort(a);for(g=0;12>g;g++)b[g]=pa(b[g]),c[g]=pa(c[g]),d[g]=pa(d[g]);this._monthsShortRegex=this._monthsRegex=new RegExp("^("+d.join("|")+")","i");this._monthsStrictRegex=new RegExp("^("+c.join("|")+")$","i");this._monthsShortStrictRegex=new RegExp("^("+b.join("|")+")$","i")}function Ka(a){var b;(b=a._a)&&-2===n(a).overflow&&(b=0>b[I]||11<b[I]?I:1>b[E]||b[E]>Ja(b[B],b[I])?E:0>b[u]||24<b[u]||
24===b[u]&&(0!==b[C]||0!==b[J]||0!==b[S])?u:0>b[C]||59<b[C]?C:0>b[J]||59<b[J]?J:0>b[S]||999<b[S]?S:-1,n(a)._overflowDayOfYear&&(b<B||b>E)&&(b=E),n(a)._overflowWeeks&&-1===b&&(b=Pb),n(a)._overflowWeekday&&-1===b&&(b=Qb),n(a).overflow=b);return a}function jb(a){!1===k.suppressDeprecationWarnings&&"undefined"!==typeof console&&console.warn&&console.warn("Deprecation warning: "+a)}function D(a,b){var c=!0;return ka(function(){c&&(jb(a+"\nArguments: "+Array.prototype.slice.call(arguments).join(", ")+"\n"+
Error().stack),c=!1);return b.apply(this,arguments)},b)}function kb(a){var b,c;b=a._i;var d=Rb.exec(b)||Sb.exec(b),g,e,f,k;if(d){n(a).iso=!0;b=0;for(c=qa.length;b<c;b++)if(qa[b][1].exec(d[1])){e=qa[b][0];g=!1!==qa[b][2];break}if(null==e)a._isValid=!1;else{if(d[3]){b=0;for(c=La.length;b<c;b++)if(La[b][1].exec(d[3])){f=(d[2]||" ")+La[b][0];break}if(null==f){a._isValid=!1;return}}if(g||null==f){if(d[4])if(Tb.exec(d[4]))k="Z";else{a._isValid=!1;return}a._f=e+(f||"")+(k||"");Ma(a)}else a._isValid=!1}}else a._isValid=
!1}function Ub(a){var b=Vb.exec(a._i);null!==b?a._d=new Date(+b[1]):(kb(a),!1===a._isValid&&(delete a._isValid,k.createFromInputFallback(a)))}function Wb(a,b,c,d,g,e,f){b=new Date(a,b,c,d,g,e,f);100>a&&0<=a&&isFinite(b.getFullYear())&&b.setFullYear(a);return b}function ra(a){var b=new Date(Date.UTC.apply(null,arguments));100>a&&0<=a&&isFinite(b.getUTCFullYear())&&b.setUTCFullYear(a);return b}function Z(a){return 0===a%4&&0!==a%100||0===a%400}function sa(a,b,c){c=7+b-c;return-((7+ra(a,0,c).getUTCDay()-
b)%7)+c-1}function lb(a,b,c,d,g){c=(7+c-d)%7;d=sa(a,d,g);d=1+7*(b-1)+c+d;0>=d?(b=a-1,a=(Z(b)?366:365)+d):d>(Z(a)?366:365)?(b=a+1,a=d-(Z(a)?366:365)):(b=a,a=d);return{year:b,dayOfYear:a}}function ga(a,b,c){var d=sa(a.year(),b,c),d=Math.floor((a.dayOfYear()-d-1)/7)+1;1>d?(a=a.year()-1,b=d+T(a,b,c)):d>T(a.year(),b,c)?(b=d-T(a.year(),b,c),a=a.year()+1):(a=a.year(),b=d);return{week:b,year:a}}function T(a,b,c){var d=sa(a,b,c);b=sa(a+1,b,c);return((Z(a)?366:365)-d+b)/7}function aa(a,b,c){return null!=a?
a:null!=b?b:c}function Na(a){var b,c=[],d;if(!a._d){d=new Date(k.now());d=a._useUTC?[d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate()]:[d.getFullYear(),d.getMonth(),d.getDate()];if(a._w&&null==a._a[E]&&null==a._a[I]){var g,e,f,h,l,m;g=a._w;if(null!=g.GG||null!=g.W||null!=g.E){if(l=1,m=4,e=aa(g.GG,a._a[B],ga(r(),1,4).year),f=aa(g.W,1),h=aa(g.E,1),1>h||7<h)b=!0}else if(l=a._locale._week.dow,m=a._locale._week.doy,e=aa(g.gg,a._a[B],ga(r(),l,m).year),f=aa(g.w,1),null!=g.d){if(h=g.d,0>h||6<h)b=!0}else if(null!=
g.e){if(h=g.e+l,0>g.e||6<g.e)b=!0}else h=l;1>f||f>T(e,l,m)?n(a)._overflowWeeks=!0:null!=b?n(a)._overflowWeekday=!0:(b=lb(e,f,h,l,m),a._a[B]=b.year,a._dayOfYear=b.dayOfYear)}a._dayOfYear&&(b=aa(a._a[B],d[B]),a._dayOfYear>(Z(b)?366:365)&&(n(a)._overflowDayOfYear=!0),b=ra(b,0,a._dayOfYear),a._a[I]=b.getUTCMonth(),a._a[E]=b.getUTCDate());for(b=0;3>b&&null==a._a[b];++b)a._a[b]=c[b]=d[b];for(;7>b;b++)a._a[b]=c[b]=null==a._a[b]?2===b?1:0:a._a[b];24===a._a[u]&&0===a._a[C]&&0===a._a[J]&&0===a._a[S]&&(a._nextDay=
!0,a._a[u]=0);a._d=(a._useUTC?ra:Wb).apply(null,c);null!=a._tzm&&a._d.setUTCMinutes(a._d.getUTCMinutes()-a._tzm);a._nextDay&&(a._a[u]=24)}}function Ma(a){if(a._f===k.ISO_8601)kb(a);else{a._a=[];n(a).empty=!0;var b=""+a._i,c,d,g,e,f,h=b.length,l=0;g=fb(a._f,a._locale).match(eb)||[];for(c=0;c<g.length;c++){e=g[c];if(d=(b.match(Nb(e,a))||[])[0])f=b.substr(0,b.indexOf(d)),0<f.length&&n(a).unusedInput.push(f),b=b.slice(b.indexOf(d)+d.length),l+=d.length;if(Y[e]){if(d?n(a).empty=!1:n(a).unusedTokens.push(e),
f=a,null!=d&&G(Ia,e))Ia[e](d,f._a,f,e)}else a._strict&&!d&&n(a).unusedTokens.push(e)}n(a).charsLeftOver=h-l;0<b.length&&n(a).unusedInput.push(b);!0===n(a).bigHour&&12>=a._a[u]&&0<a._a[u]&&(n(a).bigHour=void 0);b=a._a;c=u;h=a._locale;g=a._a[u];l=a._meridiem;null!=l&&(null!=h.meridiemHour?g=h.meridiemHour(g,l):null!=h.isPM&&((h=h.isPM(l))&&12>g&&(g+=12),h||12!==g||(g=0)));b[c]=g;Na(a);Ka(a)}}function Xb(a){if(!a._d){var b=cb(a._i);a._a=Wa([b.year,b.month,b.day||b.date,b.hour,b.minute,b.second,b.millisecond],
function(a){return a&&parseInt(a,10)});Na(a)}}function mb(a){var b=a._i,c=a._f;a._locale=a._locale||R(a._l);if(null===b||void 0===c&&""===b)return la({nullInput:!0});"string"===typeof b&&(a._i=b=a._locale.preparse(b));if(L(b))return new ca(Ka(b));if(z(c)){var d,g,e;if(0===a._f.length)n(a).invalidFormat=!0,a._d=new Date(NaN);else{for(b=0;b<a._f.length;b++)if(c=0,d=Ca({},a),null!=a._useUTC&&(d._useUTC=a._useUTC),d._f=a._f[b],Ma(d),Ba(d)&&(c+=n(d).charsLeftOver,c+=10*n(d).unusedTokens.length,n(d).score=
c,null==e||c<e))e=c,g=d;ka(a,g||d)}}else c?Ma(a):ja(b)?a._d=b:Yb(a);Ba(a)||(a._d=null);return a}function Yb(a){var b=a._i;void 0===b?a._d=new Date(k.now()):ja(b)?a._d=new Date(+b):"string"===typeof b?Ub(a):z(b)?(a._a=Wa(b.slice(0),function(a){return parseInt(a,10)}),Na(a)):"object"===typeof b?Xb(a):"number"===typeof b?a._d=new Date(b):k.createFromInputFallback(a)}function Xa(a,b,c,d,g){var e={};"boolean"===typeof c&&(d=c,c=void 0);e._isAMomentObject=!0;e._useUTC=e._isUTC=g;e._l=c;e._i=a;e._f=b;e._strict=
d;a=new ca(Ka(mb(e)));a._nextDay&&(a.add(1,"d"),a._nextDay=void 0);return a}function r(a,b,c,d){return Xa(a,b,c,d,!1)}function nb(a,b){var c,d;1===b.length&&z(b[0])&&(b=b[0]);if(!b.length)return r();c=b[0];for(d=1;d<b.length;++d)if(!b[d].isValid()||b[d][a](c))c=b[d];return c}function ta(a){a=cb(a);var b=a.year||0,c=a.quarter||0,d=a.month||0,g=a.week||0,e=a.day||0;this._milliseconds=+(a.millisecond||0)+1E3*(a.second||0)+6E4*(a.minute||0)+36E5*(a.hour||0);this._days=+e+7*g;this._months=+d+3*c+12*b;
this._data={};this._locale=R();this._bubble()}function Oa(a){return a instanceof ta}function ob(a,b){h(a,0,0,function(){var a=this.utcOffset(),d="+";0>a&&(a=-a,d="-");return d+H(~~(a/60),2)+b+H(~~a%60,2)})}function Pa(a,b){var c=(b||"").match(a)||[],c=((c[c.length-1]||[])+"").match(Zb)||["-",0,0],d=+(60*c[1])+m(c[2]);return"+"===c[0]?d:-d}function Qa(a,b){var c,d;return b._isUTC?(c=b.clone(),d=(L(a)||ja(a)?+a:+r(a))-+c,c._d.setTime(+c._d+d),k.updateOffset(c,!1),c):r(a).local()}function pb(){return this.isValid()?
this._isUTC&&0===this._offset:!1}function N(a,b){var c=a,d=null;Oa(a)?c={ms:a._milliseconds,d:a._days,M:a._months}:"number"===typeof a?(c={},b?c[b]=a:c.milliseconds=a):(d=$b.exec(a))?(c="-"===d[1]?-1:1,c={y:0,d:m(d[E])*c,h:m(d[u])*c,m:m(d[C])*c,s:m(d[J])*c,ms:m(d[S])*c}):(d=ac.exec(a))?(c="-"===d[1]?-1:1,c={y:U(d[2],c),M:U(d[3],c),d:U(d[4],c),h:U(d[5],c),m:U(d[6],c),s:U(d[7],c),w:U(d[8],c)}):null==c?c={}:"object"===typeof c&&("from"in c||"to"in c)&&(d=r(c.from),c=r(c.to),d.isValid()&&c.isValid()?
(c=Qa(c,d),d.isBefore(c)?c=qb(d,c):(c=qb(c,d),c.milliseconds=-c.milliseconds,c.months=-c.months),d=c):d={milliseconds:0,months:0},c={},c.ms=d.milliseconds,c.M=d.months);c=new ta(c);Oa(a)&&G(a,"_locale")&&(c._locale=a._locale);return c}function U(a,b){var c=a&&parseFloat(a.replace(",","."));return(isNaN(c)?0:c)*b}function qb(a,b){var c={milliseconds:0,months:0};c.months=b.month()-a.month()+12*(b.year()-a.year());a.clone().add(c.months,"M").isAfter(b)&&--c.months;c.milliseconds=+b-+a.clone().add(c.months,
"M");return c}function rb(a,b){return function(c,d){var g;null===d||isNaN(+d)||(sb[b]||(jb("moment()."+b+"(period, number) is deprecated. Please use moment()."+b+"(number, period)."),sb[b]=!0),g=c,c=d,d=g);g=N("string"===typeof c?+c:c,d);tb(this,g,a);return this}}function tb(a,b,c,d){var g=b._milliseconds,e=b._days;b=b._months;if(a.isValid()){d=null==d?!0:d;g&&a._d.setTime(+a._d+g*c);if(e&&(g=na(a,"Date")+e*c,a.isValid()))a._d["set"+(a._isUTC?"UTC":"")+"Date"](g);b&&gb(a,na(a,"Month")+b*c);d&&k.updateOffset(a,
e||b)}}function ub(a){if(void 0===a)return this._locale._abbr;a=R(a);null!=a&&(this._locale=a);return this}function vb(){return this._locale}function ua(a,b){h(0,[a,a.length],0,b)}function wb(a,b,c,d,g){var e;if(null==a)return ga(this,d,g).year;e=T(a,d,g);b>e&&(b=e);a=lb(a,b,c,d,g);a=ra(a.year,0,a.dayOfYear);this.year(a.getUTCFullYear());this.month(a.getUTCMonth());this.date(a.getUTCDate());return this}function Ra(){return this.hours()%12||12}function xb(a,b){h(a,0,0,function(){return this.localeData().meridiem(this.hours(),
this.minutes(),b)})}function yb(a,b){return b._meridiemParse}function bc(a,b){b[S]=m(1E3*("0."+a))}function zb(a){return a}function Ab(a,b,c,d){var e=R();b=W().set(d,b);return e[c](b,a)}function ha(a,b,c,d,e){"number"===typeof a&&(b=a,a=void 0);a=a||"";if(null!=b)return Ab(a,b,c,e);var f=[];for(b=0;b<d;b++)f[b]=Ab(a,b,c,e);return f}function Bb(a,b,c,d){b=N(b,c);a._milliseconds+=d*b._milliseconds;a._days+=d*b._days;a._months+=d*b._months;return a._bubble()}function Cb(a){return 0>a?Math.floor(a):Math.ceil(a)}
function O(a){return function(){return this.as(a)}}function V(a){return function(){return this._data[a]}}function cc(a,b,c,d,e){return e.relativeTime(b||1,!!c,a,d)}function va(){var a=Sa(this._milliseconds)/1E3,b=Sa(this._days),c=Sa(this._months),d,e,f;d=x(a/60);e=x(d/60);a%=60;d%=60;f=x(c/12);var c=c%12,h=this.asSeconds();return h?(0>h?"-":"")+"P"+(f?f+"Y":"")+(c?c+"M":"")+(b?b+"D":"")+(e||d||a?"T":"")+(e?e+"H":"")+(d?d+"M":"")+(a?a+"S":""):"P0D"}var Va,Da=k.momentProperties=[],Ea=!1,Q={},ma,ea=
{},eb=/(\[[^\[]*\])|(\\)?([Hh]mm(ss)?|Mo|MM?M?M?|Do|DDDo|DD?D?D?|ddd?d?|do?|w[o|w]?|W[o|W]?|Qo?|YYYYYY|YYYYY|YYYY|YY|gg(ggg?)?|GG(GGG?)?|e|E|a|A|hh?|HH?|mm?|ss?|S{1,9}|x|X|zz?|ZZ?|.)/g,oa=/(\[[^\[]*\])|(\\)?(LTS|LT|LL?L?L?|l{1,4})/g,Ga={},Y={},Db=/\d/,y=/\d\d/,Eb=/\d{3}/,Ta=/\d{4}/,wa=/[+-]?\d{6}/,t=/\d\d?/,Fb=/\d\d\d\d?/,Gb=/\d\d\d\d\d\d?/,xa=/\d{1,3}/,Ua=/\d{1,4}/,ya=/[+-]?\d{1,6}/,dc=/\d+/,za=/[+-]?\d+/,ec=/Z|[+-]\d\d:?\d\d/gi,Aa=/Z|[+-]\d\d(?::?\d\d)?/gi,ia=/[0-9]*['a-z\u00A0-\u05FF\u0700-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]+|[\u0600-\u06FF\/]+(\s*?[\u0600-\u06FF]+){1,2}/i,
Ha={},Ia={},B=0,I=1,E=2,u=3,C=4,J=5,S=6,Pb=7,Qb=8;h("M",["MM",2],"Mo",function(){return this.month()+1});h("MMM",0,0,function(a){return this.localeData().monthsShort(this,a)});h("MMMM",0,0,function(a){return this.localeData().months(this,a)});v("month","M");f("M",t);f("MM",t,y);f("MMM",function(a,b){return b.monthsShortRegex(a)});f("MMMM",function(a,b){return b.monthsRegex(a)});q(["M","MM"],function(a,b){b[I]=m(a)-1});q(["MMM","MMMM"],function(a,b,c,d){d=c._locale.monthsParse(a,d,c._strict);null!=
d?b[I]=d:n(c).invalidMonth=a});var Hb=/D[oD]?(\[[^\[\]]*\]|\s+)+MMMM?/,sb={};k.suppressDeprecationWarnings=!1;var Rb=/^\s*((?:[+-]\d{6}|\d{4})-(?:\d\d-\d\d|W\d\d-\d|W\d\d|\d\d\d|\d\d))(?:(T| )(\d\d(?::\d\d(?::\d\d(?:[.,]\d+)?)?)?)([\+\-]\d\d(?::?\d\d)?|\s*Z)?)?/,Sb=/^\s*((?:[+-]\d{6}|\d{4})(?:\d\d\d\d|W\d\d\d|W\d\d|\d\d\d|\d\d))(?:(T| )(\d\d(?:\d\d(?:\d\d(?:[.,]\d+)?)?)?)([\+\-]\d\d(?::?\d\d)?|\s*Z)?)?/,Tb=/Z|[+-]\d\d(?::?\d\d)?/,qa=[["YYYYYY-MM-DD",/[+-]\d{6}-\d\d-\d\d/],["YYYY-MM-DD",/\d{4}-\d\d-\d\d/],
["GGGG-[W]WW-E",/\d{4}-W\d\d-\d/],["GGGG-[W]WW",/\d{4}-W\d\d/,!1],["YYYY-DDD",/\d{4}-\d{3}/],["YYYY-MM",/\d{4}-\d\d/,!1],["YYYYYYMMDD",/[+-]\d{10}/],["YYYYMMDD",/\d{8}/],["GGGG[W]WWE",/\d{4}W\d{3}/],["GGGG[W]WW",/\d{4}W\d{2}/,!1],["YYYYDDD",/\d{7}/]],La=[["HH:mm:ss.SSSS",/\d\d:\d\d:\d\d\.\d+/],["HH:mm:ss,SSSS",/\d\d:\d\d:\d\d,\d+/],["HH:mm:ss",/\d\d:\d\d:\d\d/],["HH:mm",/\d\d:\d\d/],["HHmmss.SSSS",/\d\d\d\d\d\d\.\d+/],["HHmmss,SSSS",/\d\d\d\d\d\d,\d+/],["HHmmss",/\d\d\d\d\d\d/],["HHmm",/\d\d\d\d/],
["HH",/\d\d/]],Vb=/^\/?Date\((\-?\d+)/i;k.createFromInputFallback=D("moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.",function(a){a._d=new Date(a._i+(a._useUTC?" UTC":""))});h("Y",0,0,function(){var a=this.year();return 9999>=a?""+a:"+"+a});h(0,["YY",2],0,function(){return this.year()%100});h(0,["YYYY",4],0,"year");h(0,["YYYYY",5],0,"year");h(0,["YYYYYY",6,!0],
0,"year");v("year","y");f("Y",za);f("YY",t,y);f("YYYY",Ua,Ta);f("YYYYY",ya,wa);f("YYYYYY",ya,wa);q(["YYYYY","YYYYYY"],B);q("YYYY",function(a,b){b[B]=2===a.length?k.parseTwoDigitYear(a):m(a)});q("YY",function(a,b){b[B]=k.parseTwoDigitYear(a)});q("Y",function(a,b){b[B]=parseInt(a,10)});k.parseTwoDigitYear=function(a){return m(a)+(68<m(a)?1900:2E3)};var Ib=X("FullYear",!1);k.ISO_8601=function(){};var fc=D("moment().min is deprecated, use moment.min instead. https://github.com/moment/moment/issues/1548",
function(){var a=r.apply(null,arguments);return this.isValid()&&a.isValid()?a<this?this:a:la()}),gc=D("moment().max is deprecated, use moment.max instead. https://github.com/moment/moment/issues/1548",function(){var a=r.apply(null,arguments);return this.isValid()&&a.isValid()?a>this?this:a:la()});ob("Z",":");ob("ZZ","");f("Z",Aa);f("ZZ",Aa);q(["Z","ZZ"],function(a,b,c){c._useUTC=!0;c._tzm=Pa(Aa,a)});var Zb=/([\+\-]|\d\d)/gi;k.updateOffset=function(){};var $b=/(\-)?(?:(\d*)[. ])?(\d+)\:(\d+)(?:\:(\d+)\.?(\d{3})?)?/,
ac=/^(-)?P(?:(?:([0-9,.]*)Y)?(?:([0-9,.]*)M)?(?:([0-9,.]*)D)?(?:T(?:([0-9,.]*)H)?(?:([0-9,.]*)M)?(?:([0-9,.]*)S)?)?|([0-9,.]*)W)$/;N.fn=ta.prototype;var hc=rb(1,"add"),ic=rb(-1,"subtract");k.defaultFormat="YYYY-MM-DDTHH:mm:ssZ";var Jb=D("moment().lang() is deprecated. Instead, use moment().localeData() to get the language configuration. Use moment().locale() to change languages.",function(a){return void 0===a?this.localeData():this.locale(a)});h(0,["gg",2],0,function(){return this.weekYear()%100});
h(0,["GG",2],0,function(){return this.isoWeekYear()%100});ua("gggg","weekYear");ua("ggggg","weekYear");ua("GGGG","isoWeekYear");ua("GGGGG","isoWeekYear");v("weekYear","gg");v("isoWeekYear","GG");f("G",za);f("g",za);f("GG",t,y);f("gg",t,y);f("GGGG",Ua,Ta);f("gggg",Ua,Ta);f("GGGGG",ya,wa);f("ggggg",ya,wa);fa(["gggg","ggggg","GGGG","GGGGG"],function(a,b,c,d){b[d.substr(0,2)]=m(a)});fa(["gg","GG"],function(a,b,c,d){b[d]=k.parseTwoDigitYear(a)});h("Q",0,"Qo","quarter");v("quarter","Q");f("Q",Db);q("Q",
function(a,b){b[I]=3*(m(a)-1)});h("w",["ww",2],"wo","week");h("W",["WW",2],"Wo","isoWeek");v("week","w");v("isoWeek","W");f("w",t);f("ww",t,y);f("W",t);f("WW",t,y);fa(["w","ww","W","WW"],function(a,b,c,d){b[d.substr(0,1)]=m(a)});h("D",["DD",2],"Do","date");v("date","D");f("D",t);f("DD",t,y);f("Do",function(a,b){return a?b._ordinalParse:b._ordinalParseLenient});q(["D","DD"],E);q("Do",function(a,b){b[E]=m(a.match(t)[0],10)});var Kb=X("Date",!0);h("d",0,"do","day");h("dd",0,0,function(a){return this.localeData().weekdaysMin(this,
a)});h("ddd",0,0,function(a){return this.localeData().weekdaysShort(this,a)});h("dddd",0,0,function(a){return this.localeData().weekdays(this,a)});h("e",0,0,"weekday");h("E",0,0,"isoWeekday");v("day","d");v("weekday","e");v("isoWeekday","E");f("d",t);f("e",t);f("E",t);f("dd",ia);f("ddd",ia);f("dddd",ia);fa(["dd","ddd","dddd"],function(a,b,c,d){d=c._locale.weekdaysParse(a,d,c._strict);null!=d?b.d=d:n(c).invalidWeekday=a});fa(["d","e","E"],function(a,b,c,d){b[d]=m(a)});h("DDD",["DDDD",3],"DDDo","dayOfYear");
v("dayOfYear","DDD");f("DDD",xa);f("DDDD",Eb);q(["DDD","DDDD"],function(a,b,c){c._dayOfYear=m(a)});h("H",["HH",2],0,"hour");h("h",["hh",2],0,Ra);h("hmm",0,0,function(){return""+Ra.apply(this)+H(this.minutes(),2)});h("hmmss",0,0,function(){return""+Ra.apply(this)+H(this.minutes(),2)+H(this.seconds(),2)});h("Hmm",0,0,function(){return""+this.hours()+H(this.minutes(),2)});h("Hmmss",0,0,function(){return""+this.hours()+H(this.minutes(),2)+H(this.seconds(),2)});xb("a",!0);xb("A",!1);v("hour","h");f("a",
yb);f("A",yb);f("H",t);f("h",t);f("HH",t,y);f("hh",t,y);f("hmm",Fb);f("hmmss",Gb);f("Hmm",Fb);f("Hmmss",Gb);q(["H","HH"],u);q(["a","A"],function(a,b,c){c._isPm=c._locale.isPM(a);c._meridiem=a});q(["h","hh"],function(a,b,c){b[u]=m(a);n(c).bigHour=!0});q("hmm",function(a,b,c){var d=a.length-2;b[u]=m(a.substr(0,d));b[C]=m(a.substr(d));n(c).bigHour=!0});q("hmmss",function(a,b,c){var d=a.length-4,e=a.length-2;b[u]=m(a.substr(0,d));b[C]=m(a.substr(d,2));b[J]=m(a.substr(e));n(c).bigHour=!0});q("Hmm",function(a,
b,c){c=a.length-2;b[u]=m(a.substr(0,c));b[C]=m(a.substr(c))});q("Hmmss",function(a,b,c){c=a.length-4;var d=a.length-2;b[u]=m(a.substr(0,c));b[C]=m(a.substr(c,2));b[J]=m(a.substr(d))});var jc=X("Hours",!0);h("m",["mm",2],0,"minute");v("minute","m");f("m",t);f("mm",t,y);q(["m","mm"],C);var kc=X("Minutes",!1);h("s",["ss",2],0,"second");v("second","s");f("s",t);f("ss",t,y);q(["s","ss"],J);var lc=X("Seconds",!1);h("S",0,0,function(){return~~(this.millisecond()/100)});h(0,["SS",2],0,function(){return~~(this.millisecond()/
10)});h(0,["SSS",3],0,"millisecond");h(0,["SSSS",4],0,function(){return 10*this.millisecond()});h(0,["SSSSS",5],0,function(){return 100*this.millisecond()});h(0,["SSSSSS",6],0,function(){return 1E3*this.millisecond()});h(0,["SSSSSSS",7],0,function(){return 1E4*this.millisecond()});h(0,["SSSSSSSS",8],0,function(){return 1E5*this.millisecond()});h(0,["SSSSSSSSS",9],0,function(){return 1E6*this.millisecond()});v("millisecond","ms");f("S",xa,Db);f("SS",xa,y);f("SSS",xa,Eb);var F;for(F="SSSS";9>=F.length;F+=
"S")f(F,dc);for(F="S";9>=F.length;F+="S")q(F,bc);var mc=X("Milliseconds",!1);h("z",0,0,"zoneAbbr");h("zz",0,0,"zoneName");var e=ca.prototype;e.add=hc;e.calendar=function(a,b){var c=a||r(),d=Qa(c,this).startOf("day"),d=this.diff(d,"days",!0),d=-6>d?"sameElse":-1>d?"lastWeek":0>d?"lastDay":1>d?"sameDay":2>d?"nextDay":7>d?"nextWeek":"sameElse",e=b&&(M(b[d])?b[d]():b[d]);return this.format(e||this.localeData().calendar(d,this,r(c)))};e.clone=function(){return new ca(this)};e.diff=function(a,b,c){var d;
if(!this.isValid())return NaN;a=Qa(a,this);if(!a.isValid())return NaN;d=6E4*(a.utcOffset()-this.utcOffset());b=A(b);if("year"===b||"month"===b||"quarter"===b){d=12*(a.year()-this.year())+(a.month()-this.month());var e=this.clone().add(d,"months"),f;0>a-e?(f=this.clone().add(d-1,"months"),a=(a-e)/(e-f)):(f=this.clone().add(d+1,"months"),a=(a-e)/(f-e));a=-(d+a);"quarter"===b?a/=3:"year"===b&&(a/=12)}else a=this-a,a="second"===b?a/1E3:"minute"===b?a/6E4:"hour"===b?a/36E5:"day"===b?(a-d)/864E5:"week"===
b?(a-d)/6048E5:a;return c?a:x(a)};e.endOf=function(a){a=A(a);return void 0===a||"millisecond"===a?this:this.startOf(a).add(1,"isoWeek"===a?"week":a).subtract(1,"ms")};e.format=function(a){a=Fa(this,a||k.defaultFormat);return this.localeData().postformat(a)};e.from=function(a,b){return this.isValid()&&(L(a)&&a.isValid()||r(a).isValid())?N({to:this,from:a}).locale(this.locale()).humanize(!b):this.localeData().invalidDate()};e.fromNow=function(a){return this.from(r(),a)};e.to=function(a,b){return this.isValid()&&
(L(a)&&a.isValid()||r(a).isValid())?N({from:this,to:a}).locale(this.locale()).humanize(!b):this.localeData().invalidDate()};e.toNow=function(a){return this.to(r(),a)};e.get=db;e.invalidAt=function(){return n(this).overflow};e.isAfter=function(a,b){var c=L(a)?a:r(a);if(!this.isValid()||!c.isValid())return!1;b=A(w(b)?"millisecond":b);return"millisecond"===b?+this>+c:+c<+this.clone().startOf(b)};e.isBefore=function(a,b){var c=L(a)?a:r(a);if(!this.isValid()||!c.isValid())return!1;b=A(w(b)?"millisecond":
b);return"millisecond"===b?+this<+c:+this.clone().endOf(b)<+c};e.isBetween=function(a,b,c){return this.isAfter(a,c)&&this.isBefore(b,c)};e.isSame=function(a,b){var c=L(a)?a:r(a);if(!this.isValid()||!c.isValid())return!1;b=A(b||"millisecond");if("millisecond"===b)return+this===+c;c=+c;return+this.clone().startOf(b)<=c&&c<=+this.clone().endOf(b)};e.isSameOrAfter=function(a,b){return this.isSame(a,b)||this.isAfter(a,b)};e.isSameOrBefore=function(a,b){return this.isSame(a,b)||this.isBefore(a,b)};e.isValid=
function(){return Ba(this)};e.lang=Jb;e.locale=ub;e.localeData=vb;e.max=gc;e.min=fc;e.parsingFlags=function(){return ka({},n(this))};e.set=db;e.startOf=function(a){a=A(a);switch(a){case "year":this.month(0);case "quarter":case "month":this.date(1);case "week":case "isoWeek":case "day":this.hours(0);case "hour":this.minutes(0);case "minute":this.seconds(0);case "second":this.milliseconds(0)}"week"===a&&this.weekday(0);"isoWeek"===a&&this.isoWeekday(1);"quarter"===a&&this.month(3*Math.floor(this.month()/
3));return this};e.subtract=ic;e.toArray=function(){return[this.year(),this.month(),this.date(),this.hour(),this.minute(),this.second(),this.millisecond()]};e.toObject=function(){return{years:this.year(),months:this.month(),date:this.date(),hours:this.hours(),minutes:this.minutes(),seconds:this.seconds(),milliseconds:this.milliseconds()}};e.toDate=function(){return this._offset?new Date(+this):this._d};e.toISOString=function(){var a=this.clone().utc();return 0<a.year()&&9999>=a.year()?M(Date.prototype.toISOString)?
this.toDate().toISOString():Fa(a,"YYYY-MM-DD[T]HH:mm:ss.SSS[Z]"):Fa(a,"YYYYYY-MM-DD[T]HH:mm:ss.SSS[Z]")};e.toJSON=function(){return this.isValid()?this.toISOString():"null"};e.toString=function(){return this.clone().locale("en").format("ddd MMM DD YYYY HH:mm:ss [GMT]ZZ")};e.unix=function(){return Math.floor(+this/1E3)};e.valueOf=function(){return+this._d-6E4*(this._offset||0)};e.creationData=function(){return{input:this._i,format:this._f,locale:this._locale,isUTC:this._isUTC,strict:this._strict}};
e.year=Ib;e.isLeapYear=function(){return Z(this.year())};e.weekYear=function(a){return wb.call(this,a,this.week(),this.weekday(),this.localeData()._week.dow,this.localeData()._week.doy)};e.isoWeekYear=function(a){return wb.call(this,a,this.isoWeek(),this.isoWeekday(),1,4)};e.quarter=e.quarters=function(a){return null==a?Math.ceil((this.month()+1)/3):this.month(3*(a-1)+this.month()%3)};e.month=hb;e.daysInMonth=function(){return Ja(this.year(),this.month())};e.week=e.weeks=function(a){var b=this.localeData().week(this);
return null==a?b:this.add(7*(a-b),"d")};e.isoWeek=e.isoWeeks=function(a){var b=ga(this,1,4).week;return null==a?b:this.add(7*(a-b),"d")};e.weeksInYear=function(){var a=this.localeData()._week;return T(this.year(),a.dow,a.doy)};e.isoWeeksInYear=function(){return T(this.year(),1,4)};e.date=Kb;e.day=e.days=function(a){if(!this.isValid())return null!=a?this:NaN;var b=this._isUTC?this._d.getUTCDay():this._d.getDay();if(null!=a){var c=this.localeData();"string"===typeof a&&(isNaN(a)?(a=c.weekdaysParse(a),
a="number"===typeof a?a:null):a=parseInt(a,10));return this.add(a-b,"d")}return b};e.weekday=function(a){if(!this.isValid())return null!=a?this:NaN;var b=(this.day()+7-this.localeData()._week.dow)%7;return null==a?b:this.add(a-b,"d")};e.isoWeekday=function(a){return this.isValid()?null==a?this.day()||7:this.day(this.day()%7?a:a-7):null!=a?this:NaN};e.dayOfYear=function(a){var b=Math.round((this.clone().startOf("day")-this.clone().startOf("year"))/864E5)+1;return null==a?b:this.add(a-b,"d")};e.hour=
e.hours=jc;e.minute=e.minutes=kc;e.second=e.seconds=lc;e.millisecond=e.milliseconds=mc;e.utcOffset=function(a,b){var c=this._offset||0,d;return this.isValid()?null!=a?("string"===typeof a?a=Pa(Aa,a):16>Math.abs(a)&&(a*=60),!this._isUTC&&b&&(d=15*-Math.round(this._d.getTimezoneOffset()/15)),this._offset=a,this._isUTC=!0,null!=d&&this.add(d,"m"),c!==a&&(!b||this._changeInProgress?tb(this,N(a-c,"m"),1,!1):this._changeInProgress||(this._changeInProgress=!0,k.updateOffset(this,!0),this._changeInProgress=
null)),this):this._isUTC?c:15*-Math.round(this._d.getTimezoneOffset()/15):null!=a?this:NaN};e.utc=function(a){return this.utcOffset(0,a)};e.local=function(a){this._isUTC&&(this.utcOffset(0,a),this._isUTC=!1,a&&this.subtract(15*-Math.round(this._d.getTimezoneOffset()/15),"m"));return this};e.parseZone=function(){this._tzm?this.utcOffset(this._tzm):"string"===typeof this._i&&this.utcOffset(Pa(ec,this._i));return this};e.hasAlignedHourOffset=function(a){if(!this.isValid())return!1;a=a?r(a).utcOffset():
0;return 0===(this.utcOffset()-a)%60};e.isDST=function(){return this.utcOffset()>this.clone().month(0).utcOffset()||this.utcOffset()>this.clone().month(5).utcOffset()};e.isDSTShifted=function(){if(!w(this._isDSTShifted))return this._isDSTShifted;var a={};Ca(a,this);a=mb(a);if(a._a){var b=a._isUTC?W(a._a):r(a._a);this._isDSTShifted=this.isValid()&&0<Ya(a._a,b.toArray())}else this._isDSTShifted=!1;return this._isDSTShifted};e.isLocal=function(){return this.isValid()?!this._isUTC:!1};e.isUtcOffset=function(){return this.isValid()?
this._isUTC:!1};e.isUtc=pb;e.isUTC=pb;e.zoneAbbr=function(){return this._isUTC?"UTC":""};e.zoneName=function(){return this._isUTC?"Coordinated Universal Time":""};e.dates=D("dates accessor is deprecated. Use date instead.",Kb);e.months=D("months accessor is deprecated. Use month instead",hb);e.years=D("years accessor is deprecated. Use year instead",Ib);e.zone=D("moment().zone is deprecated, use moment().utcOffset instead. https://github.com/moment/moment/issues/1779",function(a,b){return null!=a?
("string"!==typeof a&&(a=-a),this.utcOffset(a,b),this):-this.utcOffset()});var l=Za.prototype;l._calendar={sameDay:"[Today at] LT",nextDay:"[Tomorrow at] LT",nextWeek:"dddd [at] LT",lastDay:"[Yesterday at] LT",lastWeek:"[Last] dddd [at] LT",sameElse:"L"};l.calendar=function(a,b,c){a=this._calendar[a];return M(a)?a.call(b,c):a};l._longDateFormat={LTS:"h:mm:ss A",LT:"h:mm A",L:"MM/DD/YYYY",LL:"MMMM D, YYYY",LLL:"MMMM D, YYYY h:mm A",LLLL:"dddd, MMMM D, YYYY h:mm A"};l.longDateFormat=function(a){var b=
this._longDateFormat[a],c=this._longDateFormat[a.toUpperCase()];if(b||!c)return b;this._longDateFormat[a]=c.replace(/MMMM|MM|DD|dddd/g,function(a){return a.slice(1)});return this._longDateFormat[a]};l._invalidDate="Invalid date";l.invalidDate=function(){return this._invalidDate};l._ordinal="%d";l.ordinal=function(a){return this._ordinal.replace("%d",a)};l._ordinalParse=/\d{1,2}/;l.preparse=zb;l.postformat=zb;l._relativeTime={future:"in %s",past:"%s ago",s:"a few seconds",m:"a minute",mm:"%d minutes",
h:"an hour",hh:"%d hours",d:"a day",dd:"%d days",M:"a month",MM:"%d months",y:"a year",yy:"%d years"};l.relativeTime=function(a,b,c,d){var e=this._relativeTime[c];return M(e)?e(a,b,c,d):e.replace(/%d/i,a)};l.pastFuture=function(a,b){var c=this._relativeTime[0<a?"future":"past"];return M(c)?c(b):c.replace(/%s/i,b)};l.set=function(a){var b,c;for(c in a)b=a[c],M(b)?this[c]=b:this["_"+c]=b;this._ordinalParseLenient=new RegExp(this._ordinalParse.source+"|"+/\d{1,2}/.source)};l.months=function(a,b){return z(this._months)?
this._months[a.month()]:this._months[Hb.test(b)?"format":"standalone"][a.month()]};l._months="January February March April May June July August September October November December".split(" ");l.monthsShort=function(a,b){return z(this._monthsShort)?this._monthsShort[a.month()]:this._monthsShort[Hb.test(b)?"format":"standalone"][a.month()]};l._monthsShort="Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" ");l.monthsParse=function(a,b,c){var d,e;this._monthsParse||(this._monthsParse=[],this._longMonthsParse=
[],this._shortMonthsParse=[]);for(d=0;12>d;d++)if(e=W([2E3,d]),c&&!this._longMonthsParse[d]&&(this._longMonthsParse[d]=new RegExp("^"+this.months(e,"").replace(".","")+"$","i"),this._shortMonthsParse[d]=new RegExp("^"+this.monthsShort(e,"").replace(".","")+"$","i")),c||this._monthsParse[d]||(e="^"+this.months(e,"")+"|^"+this.monthsShort(e,""),this._monthsParse[d]=new RegExp(e.replace(".",""),"i")),c&&"MMMM"===b&&this._longMonthsParse[d].test(a)||c&&"MMM"===b&&this._shortMonthsParse[d].test(a)||!c&&
this._monthsParse[d].test(a))return d};l._monthsRegex=ia;l.monthsRegex=function(a){return this._monthsParseExact?(G(this,"_monthsRegex")||ib.call(this),a?this._monthsStrictRegex:this._monthsRegex):this._monthsStrictRegex&&a?this._monthsStrictRegex:this._monthsRegex};l._monthsShortRegex=ia;l.monthsShortRegex=function(a){return this._monthsParseExact?(G(this,"_monthsRegex")||ib.call(this),a?this._monthsShortStrictRegex:this._monthsShortRegex):this._monthsShortStrictRegex&&a?this._monthsShortStrictRegex:
this._monthsShortRegex};l.week=function(a){return ga(a,this._week.dow,this._week.doy).week};l._week={dow:0,doy:6};l.firstDayOfYear=function(){return this._week.doy};l.firstDayOfWeek=function(){return this._week.dow};l.weekdays=function(a,b){return z(this._weekdays)?this._weekdays[a.day()]:this._weekdays[this._weekdays.isFormat.test(b)?"format":"standalone"][a.day()]};l._weekdays="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" ");l.weekdaysMin=function(a){return this._weekdaysMin[a.day()]};
l._weekdaysMin="Su Mo Tu We Th Fr Sa".split(" ");l.weekdaysShort=function(a){return this._weekdaysShort[a.day()]};l._weekdaysShort="Sun Mon Tue Wed Thu Fri Sat".split(" ");l.weekdaysParse=function(a,b,c){var d,e;this._weekdaysParse||(this._weekdaysParse=[],this._minWeekdaysParse=[],this._shortWeekdaysParse=[],this._fullWeekdaysParse=[]);for(d=0;7>d;d++)if(e=r([2E3,1]).day(d),c&&!this._fullWeekdaysParse[d]&&(this._fullWeekdaysParse[d]=new RegExp("^"+this.weekdays(e,"").replace(".",".?")+"$","i"),this._shortWeekdaysParse[d]=
new RegExp("^"+this.weekdaysShort(e,"").replace(".",".?")+"$","i"),this._minWeekdaysParse[d]=new RegExp("^"+this.weekdaysMin(e,"").replace(".",".?")+"$","i")),this._weekdaysParse[d]||(e="^"+this.weekdays(e,"")+"|^"+this.weekdaysShort(e,"")+"|^"+this.weekdaysMin(e,""),this._weekdaysParse[d]=new RegExp(e.replace(".",""),"i")),c&&"dddd"===b&&this._fullWeekdaysParse[d].test(a)||c&&"ddd"===b&&this._shortWeekdaysParse[d].test(a)||c&&"dd"===b&&this._minWeekdaysParse[d].test(a)||!c&&this._weekdaysParse[d].test(a))return d};
l.isPM=function(a){return"p"===(a+"").toLowerCase().charAt(0)};l._meridiemParse=/[ap]\.?m?\.?/i;l.meridiem=function(a,b,c){return 11<a?c?"pm":"PM":c?"am":"AM"};da("en",{ordinalParse:/\d{1,2}(th|st|nd|rd)/,ordinal:function(a){var b=a%10,b=1===m(a%100/10)?"th":1===b?"st":2===b?"nd":3===b?"rd":"th";return a+b}});k.lang=D("moment.lang is deprecated. Use moment.locale instead.",da);k.langData=D("moment.langData is deprecated. Use moment.localeData instead.",R);var K=Math.abs,nc=O("ms"),oc=O("s"),pc=O("m"),
qc=O("h"),rc=O("d"),sc=O("w"),tc=O("M"),uc=O("y"),vc=V("milliseconds"),wc=V("seconds"),xc=V("minutes"),yc=V("hours"),zc=V("days"),Ac=V("months"),Bc=V("years"),ba=Math.round,P={s:45,m:45,h:22,d:26,M:11},Sa=Math.abs,p=ta.prototype;p.abs=function(){var a=this._data;this._milliseconds=K(this._milliseconds);this._days=K(this._days);this._months=K(this._months);a.milliseconds=K(a.milliseconds);a.seconds=K(a.seconds);a.minutes=K(a.minutes);a.hours=K(a.hours);a.months=K(a.months);a.years=K(a.years);return this};
p.add=function(a,b){return Bb(this,a,b,1)};p.subtract=function(a,b){return Bb(this,a,b,-1)};p.as=function(a){var b,c=this._milliseconds;a=A(a);if("month"===a||"year"===a)return b=this._days+c/864E5,b=this._months+4800*b/146097,"month"===a?b:b/12;b=this._days+Math.round(146097*this._months/4800);switch(a){case "week":return b/7+c/6048E5;case "day":return b+c/864E5;case "hour":return 24*b+c/36E5;case "minute":return 1440*b+c/6E4;case "second":return 86400*b+c/1E3;case "millisecond":return Math.floor(864E5*
b)+c;default:throw Error("Unknown unit "+a);}};p.asMilliseconds=nc;p.asSeconds=oc;p.asMinutes=pc;p.asHours=qc;p.asDays=rc;p.asWeeks=sc;p.asMonths=tc;p.asYears=uc;p.valueOf=function(){return this._milliseconds+864E5*this._days+this._months%12*2592E6+31536E6*m(this._months/12)};p._bubble=function(){var a=this._milliseconds,b=this._days,c=this._months,d=this._data;0<=a&&0<=b&&0<=c||0>=a&&0>=b&&0>=c||(a+=864E5*Cb(146097*c/4800+b),c=b=0);d.milliseconds=a%1E3;a=x(a/1E3);d.seconds=a%60;a=x(a/60);d.minutes=
a%60;a=x(a/60);d.hours=a%24;b+=x(a/24);a=x(4800*b/146097);c+=a;b-=Cb(146097*a/4800);a=x(c/12);d.days=b;d.months=c%12;d.years=a;return this};p.get=function(a){a=A(a);return this[a+"s"]()};p.milliseconds=vc;p.seconds=wc;p.minutes=xc;p.hours=yc;p.days=zc;p.weeks=function(){return x(this.days()/7)};p.months=Ac;p.years=Bc;p.humanize=function(a){var b=this.localeData(),c;c=!a;var d=N(this).abs(),e=ba(d.as("s")),f=ba(d.as("m")),h=ba(d.as("h")),k=ba(d.as("d")),l=ba(d.as("M")),d=ba(d.as("y")),e=e<P.s&&["s",
e]||1>=f&&["m"]||f<P.m&&["mm",f]||1>=h&&["h"]||h<P.h&&["hh",h]||1>=k&&["d"]||k<P.d&&["dd",k]||1>=l&&["M"]||l<P.M&&["MM",l]||1>=d&&["y"]||["yy",d];e[2]=c;e[3]=0<+this;e[4]=b;c=cc.apply(null,e);a&&(c=b.pastFuture(+this,c));return b.postformat(c)};p.toISOString=va;p.toString=va;p.toJSON=va;p.locale=ub;p.localeData=vb;p.toIsoString=D("toIsoString() is deprecated. Please use toISOString() instead (notice the capitals)",va);p.lang=Jb;h("X",0,0,"unix");h("x",0,0,"valueOf");f("x",za);f("X",/[+-]?\d+(\.\d{1,3})?/);
q("X",function(a,b,c){c._d=new Date(1E3*parseFloat(a,10))});q("x",function(a,b,c){c._d=new Date(m(a))});k.version="2.11.1";Va=r;k.fn=e;k.min=function(){var a=[].slice.call(arguments,0);return nb("isBefore",a)};k.max=function(){var a=[].slice.call(arguments,0);return nb("isAfter",a)};k.now=function(){return Date.now?Date.now():+new Date};k.utc=W;k.unix=function(a){return r(1E3*a)};k.months=function(a,b){return ha(a,b,"months",12,"month")};k.isDate=ja;k.locale=da;k.invalid=la;k.duration=N;k.isMoment=
L;k.weekdays=function(a,b){return ha(a,b,"weekdays",7,"day")};k.parseZone=function(){return r.apply(null,arguments).parseZone()};k.localeData=R;k.isDuration=Oa;k.monthsShort=function(a,b){return ha(a,b,"monthsShort",12,"month")};k.weekdaysMin=function(a,b){return ha(a,b,"weekdaysMin",7,"day")};k.defineLocale=bb;k.weekdaysShort=function(a,b){return ha(a,b,"weekdaysShort",7,"day")};k.normalizeUnits=A;k.relativeTimeThreshold=function(a,b){if(void 0===P[a])return!1;if(void 0===b)return P[a];P[a]=b;return!0};
k.prototype=e;return k});
