name: 'Build/Run End-to-End Tests'

on:
  push:
    branches: [SWC-6514]
jobs:
  build-and-run-e2e:
    runs-on: ubuntu-latest
    env:
      CONTAINER_NAME: 'swc-tomcat'
      CI: true
    steps:
      - uses: actions/checkout@v3
      - name: Build SWC
        uses: ./.github/workflows/build
      - name: Run SWC on Tomcat
        run: |
          docker run \
            --name $CONTAINER_NAME \
            -d --rm \
            -p 8888:8080 \
            -v "/$(pwd)/target/portal-develop-SNAPSHOT.war:/usr/local/tomcat/webapps/ROOT.war" \
            -v "/$(pwd)/e2e_workflow/settings.xml":/root/.m2/settings.xml \
            tomcat:9.0
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        env:
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
        run: yarn playwright test
      - name: Upload Playwright Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Stop Tomcat
        run: docker stop $CONTAINER_NAME
