name: 'Build/Run End-to-End Tests'

on: push
jobs:
  playwright-tests:
    if: ${{ github.ref_name == 'develop' || startsWith(github.ref_name, 'release-') || github.actor == github.repository_owner }}
    runs-on: ${{ github.repository_owner == 'Sage-Bionetworks' && 'ubuntu-22.04-4core-16GBRAM-150GBSSD' || 'macos-latest' }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        shard: [1/3, 2/3, 3/3]
    env:
      CONTAINER_NAME: 'swc-tomcat'
      CI: true
    steps:
      - uses: actions/checkout@v3
      - name: Setup docker (missing on MacOS)
        if: runner.os == 'macos'
        run: |
          brew install docker
          colima start
      - name: Build SWC
        uses: ./.github/workflows/build
      - name: Run SWC on Tomcat
        run: |
          docker run \
            --name "${CONTAINER_NAME}" \
            -d --rm \
            -p 8888:8080 \
            -v "/$(pwd)/target/portal-develop-SNAPSHOT.war:/usr/local/tomcat/webapps/ROOT.war" \
            -v "/$(pwd)/e2e_workflow/settings.xml":/root/.m2/settings.xml \
            tomcat:9.0
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps
      - name: Run Playwright tests
        env:
          ADMIN_PAT: ${{ secrets.ADMIN_PAT }}
        run: yarn playwright test --shard ${{ matrix.shard }}
      - name: Upload blob report to GitHub Actions Artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: all-blob-reports
          path: blob-report
          retention-days: 1
      - name: Stop Tomcat
        if: always()
        run: docker stop "${CONTAINER_NAME}"
      - name: Stop Colima
        if: runner.os == 'macos'
        run: colima stop
  merge-reports:
    # Merge reports after playwright-tests, even if some shards have failed
    if: always()
    needs: [playwright-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Download blob reports from GitHub Actions Artifacts
        uses: actions/download-artifact@v3
        with:
          name: all-blob-reports
          path: all-blob-reports
      - name: Merge into HTML Report
        run: yarn playwright merge-reports --reporter html ./all-blob-reports
      - name: Upload HTML report
        uses: actions/upload-artifact@v3
        with:
          name: html-report--attempt-${{ github.run_attempt }}
          path: playwright-report
          retention-days: 14
