name: build
on:
  workflow_call:
    inputs:
      mvn_goal:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: corretto
          cache: 'maven'
          server-id: sagebionetworks
          server-username: MAVEN_USERNAME
          server-password: MAVEN_USERPWD
      - name: Version artifacts
        if: ${{ inputs.mvn_goal != 'deploy' }}
        run: chmod 777 pomSnapshotToGitHash.sh && ./pomSnapshotToGitHash.sh
      - name: Build with Maven
        run: echo mvn -B ${{ inputs.mvn_goal }} --file pom.xml
        env:
          MAVEN_USERNAME: ${{ secrets.PLATFORM_ARTIFACTORY_USER }}
          MAVEN_USERPWD: ${{ secrets.PLATFORM_ARTIFACTORY_PWD }}
